@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 09 14:58:35 -0800 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_traffic_light_fsm_behav -key {Behavioral:sim_1:Functional:tb_traffic_light_fsm} -tclbatch tb_traffic_light_fsm.tcl -view C:/Users/anayf/TrafficLightSimulator/tb_green_counter_behav1.wcfg -view C:/Users/anayf/TrafficLightSimulator/tb_traffic_light_fsm_behav.wcfg -log simulate.log"
call xsim  tb_traffic_light_fsm_behav -key {Behavioral:sim_1:Functional:tb_traffic_light_fsm} -tclbatch tb_traffic_light_fsm.tcl -view C:/Users/anayf/TrafficLightSimulator/tb_green_counter_behav1.wcfg -view C:/Users/anayf/TrafficLightSimulator/tb_traffic_light_fsm_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
